- name: add backup mongodb user
  mongodb_user:
    database: admin
    roles: "backup,read"
    name: "backups"
    password: "{{ mongodb_backups_password }}"
    login_user: "{{ mongodb_secured_username }}"
    login_password: "{{ mongodb_secured_password }}"
    state: present
  sudo: yes


- name: copy backup utility over to remote
  copy:
    src: backup-mongo.sh
    dest: /usr/share/backup-mongo.sh
    group: root
    owner: root
    mode: 700
  sudo: yes


- name: setup cron job to backup nightly
  template:
    src: backup-mongo-cron.j2
    dest: /etc/cron.d/mongodb-backup
    group: root
    owner: root
    mode: 700
  sudo: yes
