- name: copy vimrc to remote
  copy:
    src: vimrc
    dest: /home/orch/.vimrc
    group: orch
    owner: orch
    mode: 755

- name: copy vim folder to remote
  copy:
    src: vim
    dest: /home/orch
    group: orch
    owner: orch
    mode: 755
    directory_mode: 755
