- name: perform safe upgrades on system packages
  apt:
    update_cache: yes
    upgrade: safe
  sudo: yes


- name: reboot system if required
  command: shutdown -r now 'rebooting to complete system upgrade'
           removes=/var/run/reboot-required
  async: 0
  poll: 0
  ignore_errors: true
  sudo: yes
  when: allow_reboot is defined and allow_reboot


- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }}
                state=started
                timeout=60
                delay=20
  sudo: false
  when: allow_reboot is defined and allow_reboot
